name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libasound2-dev libudev-dev
    - name: Check
      run: cargo --version && cargo check --verbose
    - name: Run tests
      run: cargo test --release --verbose
